version: "3"
services:
  app:
    container_name: idea-server-deploy
    build:
      context: ./
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "80:8080"
    command: ./main
    
  dev:
    container_name: idea-server-develop
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: devlop
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      
  redis:
    container_name: idea-server
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
    - type: volume
      source: idea-server-volume
      target: /data
volumes:
  idea-server-volume:
    name: idea-server