version: "3"
services:
  app:
    container_name: tech-guide-deploy
    build:
      context: ./
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "80:8080"
    command: ./main
    
  dev:
    container_name: tech-guide-develop
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: devlop
    ports:
      - "8080:8080"
    volumes:
      - .:/app